---
- name: Ensure kube-dns configuration
  template:
    src: addons/kube-dns.j2
    dest: /etc/kubernetes/addons/kube-dns.yaml
  register: kubedns

- name: Installing kube-dns
  command: kubectl apply -f /etc/kubernetes/addons/kube-dns.yaml
  when: kubedns|changed
