---
- name: Create CNI plugin directory
  file:
    state: directory
    path: /opt/cni/bin
    recurse: yes

- name: Install CNI plugins
  unarchive:
    src: https://github.com/containernetworking/plugins/releases/download/v{{ cni_version }}/cni-plugins-amd64-v{{ cni_version }}.tgz
    dest: /opt/cni/bin
    remote_src: yes
