---
- name: Check if kube-dns is running
  command: kubectl --namespace=kube-system get deployment kube-dns
  run_once: yes
  ignore_errors: yes
  register: kubedns_installed

- when: kubedns_installed.rc > 0
  run_once: yes
  block:
  - name: Ensure kube-dns configuration
    template:
      src: addons/kube-dns.j2
      dest: /tmp/kube-dns.yml
  - name: Apply kube-dns manifest
    shell: kubectl apply -f /tmp/kube-dns.yml
  always:
  - name: Remove kube-dns manifest
    file:
      state: absent
      path: /tmp/kube-dns.yml