---
- name: Download kube-apiserver
  get_url:
    url: "https://storage.googleapis.com/kubernetes-release/release/v{{ k8s_version }}/bin/linux/amd64/kube-apiserver"
    checksum: "{{ k8s_kubeapiserver_checksum }}"
    dest: /usr/local/bin/kube-apiserver
    mode: 0755

- name: Install kube-apiserver systemd configuration
  template:
    src: systemd/kube-apiserver.j2
    dest: /etc/systemd/system/kube-apiserver.service
    owner: root
    group: root
    mode: 0664
  notify:
  - Reload systemd daemon
  - Restart kube-apiserver

- name: Allow apiserver traffic internally
  ufw: rule=allow port=6443 proto=tcp src={{ k8s_internal_subnet }}
  with_items: "{{ groups['k8s-master'] }}"

- name: Ensure kube-apiserver is started at boot
  service: name=kube-apiserver daemon_reload=yes state=started enabled=yes
